In [2]:
import requests
import pandas as pd
from pandas_datareader import data

In [17]:
#https://pandas-datareader.readthedocs.io/en/latest/remote_data.html
#https://github.com/rsvp/fecon235/issues/7
#https://www.learndatasci.com/tutorials/python-finance-part-yahoo-finance-api-pandas-matplotlib/
#https://www.geeksforgeeks.org/twitter-sentiment-analysis-using-python/
#https://github.com/kartik-joshi/Stock-predection
#https://snap.stanford.edu/data/twitter7.html
#https://github.com/shaypal5/awesome-twitter-data
#https://www.kaggle.com/kazanova/sentiment140

In [13]:
#def get_google_data(start_date, end_date, *args):
key = "T9Y563WVTXPFUZT5" #alpha_vantage

In [11]:
start_date = '2018-01-01'
end_date = '2018-12-01'

# User pandas_reader.data.DataReader to load the desired data. As simple as that.
panel_data = data.DataReader('AAPL', 'iex', start_date, end_date)

In [12]:
panel_data

                open      high       low     close    volume
date
2018-01-02  167.6431  169.7514  166.7564  169.7120  25555934
2018-01-03  169.9780  171.9682  169.4165  169.6825  29517899
2018-01-04  169.9879  170.9041  169.5347  170.4707  22434597
2018-01-05  170.8746  172.7760  170.4904  172.4115  23660018
2018-01-08  171.7711  173.0125  171.3573  171.7711  20567766
2018-01-09  171.9682  172.4706  170.8450  171.7514  21583997
2018-01-10  170.5987  171.7219  170.4411  171.7120  23959895
2018-01-11  172.0076  172.8929  171.9091  172.6874  18667729
2018-01-12  173.5741  174.7366  173.0519  174.4706  25418080
2018-01-16  175.2686  176.7366  173.5346  173.5839  29565947
2018-01-17  173.5445  176.5986  172.4805  176.4509  34386836
2018-01-18  176.7169  177.4361  175.6134  176.6085  31193352
2018-01-19  175.9681  176.9238  174.7859  175.8203  32425067
2018-01-22  174.6775  175.1504  173.9894  174.3819  27108551
2018-01-23  174.6775  176.7858  174.2046  174.4213  32689146
2018-01-24  174.6282  174.6775  170.6381  171.6430  51105090
2018-01-25  171.9238  172.3623  168.0076  168.5790  41529004
2018-01-26  169.4559  169.4559  167.5446  168.9731  39143011
2018-01-29  167.6431  167.6431  164.5988  165.4756  50640406
2018-01-30  163.0767  164.8944  162.2639  164.5003  46048185
2018-01-31  164.4018  165.9502  164.0372  164.9535  32478930
2018-02-01  164.6924  166.1259  164.2934  165.2983  47230787
2018-02-02  163.5446  164.3328  157.7319  158.1260  86593825
2018-02-05  156.7467  161.4560  153.6925  154.1753  72738522
2018-02-06  152.5399  161.2984  151.7221  160.6186  68243838
2018-02-07  160.6728  160.9831  156.7157  157.1802  51608580
2018-02-08  157.9191  158.6186  152.7369  152.8551  54390516
2018-02-09  155.3777  156.1889  148.6213  154.7248  70672608
2018-02-12  156.7923  162.1242  155.8130  160.9569  60819539
2018-02-13  160.2051  162.9750  159.9084  162.5694  32549163
...              ...       ...       ...       ...       ...
2018-10-19  217.3018  220.4907  216.6740  218.5475  33078726
2018-10-22  219.0258  222.5834  218.1787  219.8828  28792082
2018-10-23  215.0796  222.4738  213.9535  221.9556  38767846
2018-10-24  221.8260  223.4504  213.7940  214.3421  40925163
2018-10-25  216.9530  220.6103  215.9964  219.0358  29855768
2018-10-26  215.1493  219.4244  211.9305  215.5479  47258375
2018-10-29  218.4279  218.9261  205.3734  211.5020  45935520
2018-10-30  210.4158  214.4318  208.5424  212.5584  36659990
2018-10-31  216.1259  219.6835  215.8668  218.0990  38358933
2018-11-01  218.2884  221.5869  216.0562  221.4473  58323180
2018-11-02  208.8214  212.9071  204.7157  206.7586  91328654
2018-11-05  203.5896  203.6793  197.4810  200.8891  66163669
2018-11-06  201.2179  204.0082  200.9887  203.0615  31882881
2018-11-07  205.2538  209.3296  203.4202  209.2200  33424434
2018-11-08  209.9800  210.1200  206.7500  208.4900  25362636
2018-11-09  205.5500  206.0100  202.2500  204.4700  34365750
2018-11-12  199.0000  199.8500  193.7900  194.1700  51135518
2018-11-13  191.6300  197.1800  191.4501  192.2300  46882936
2018-11-14  193.9000  194.4800  185.9300  186.8000  60800957
2018-11-15  188.3900  191.9700  186.9000  191.4100  46478801
2018-11-16  190.5000  194.9695  189.4600  193.5300  36928253
2018-11-19  190.0000  190.7000  184.9900  185.8600  41920872
2018-11-20  178.3700  181.4700  175.5100  176.9800  67825247
2018-11-21  179.7300  180.2700  176.5500  176.7800  31124210
2018-11-23  174.9400  176.5950  172.1000  172.2900  23623972
2018-11-26  174.2400  174.9500  170.2600  174.6200  44998520
2018-11-27  171.5100  174.7700  170.8800  174.2400  41387377
2018-11-28  176.7300  181.2900  174.9300  180.9400  46062539
2018-11-29  182.6600  182.8000  177.7000  179.5500  41769992
2018-11-30  180.2900  180.3300  177.0300  178.5800  39531549

[232 rows x 5 columns]